version: '3.7'
services:
  terraform:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - TERRAFORM_VERSION=0.14.5
    tty: true
    volumes:
      - .:/data
      - $HOME/.aws:/root/.aws
